### PR TITLE
Use util instead of duplication in threadpool

### PR DESCRIPTION
**Pull request by palhaland**
I created some temp variables in get_seed as a SIGTERM was generated without it when I compiled using zig.

### CODE REVIEW

**Comment by wiedehopf** [comment]
threadpool is its own library.

**Comment by wiedehopf** [comment]
How do the temp vars help, explain.

**Comment by wiedehopf** [comment]
Yeah the temp vars don't do anything i think but i can make sure the casting is better to int64_t
Maybe that was the issue.

**Comment by palhaland** [comment]
I guess it could be the casting. I found it strange as well that it made a difference.

**Comment by wiedehopf** [comment]
Please report if you continue seeing the SIGTERM issue with the change i made.
If you do, let's get some gdb involved or something.
SIGTERM also seems like a weird signal, how would that even happen?

**Pull request closed without merging**
